version: '3.4'

services:
  ampprojectremapping:
    image: ampprojectremapping
    build:
      context: node_modules/@ampproject/remapping
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 4200:4200
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "dist/remapping.umd.js"]
