version: '3.4'

services:
  ampprojectremapping:
    image: ampprojectremapping
    build:
      context: node_modules/@ampproject/remapping
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4200:4200
